version: '3.8'

services:
  web:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    container_name: skillpath-pro-web
    working_dir: /workspaces/skillpath-pro-web
    volumes:
      - ../..:/workspaces:cached

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:api

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  api:
    image: mcr.microsoft.com/devcontainers/java:1-21-bookworm
    container_name: skillpath-pro-api
    working_dir: /workspaces/skillpath-pro-api

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
